/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      spacing: {
        gutter: '24px',
        'unit-sm': '8px',
        'container-max': '1280px',
        'unit-xl': '48px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'unit-xs': '4px',
        'unit-lg': '24px',
        'unit-md': '16px',
      },
      fontFamily: {
        'headline-xl': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Material Design 3 tokens
        "md-primary": "#002045",
        "md-primary-container": "#1a365d",
        "md-primary-fixed": "#d6e3ff",
        "md-primary-fixed-dim": "#adc7f7",
        "md-on-primary": "#ffffff",
        "md-on-primary-container": "#86a0cd",
        "md-on-primary-fixed": "#001b3c",
        "md-secondary": "#875200",
        "md-secondary-container": "#ffb55c",
        "md-secondary-fixed": "#ffddba",
        "md-secondary-fixed-dim": "#ffb866",
        "md-on-secondary": "#ffffff",
        "md-on-secondary-container": "#744600",
        "md-on-secondary-fixed": "#2b1700",
        "md-on-secondary-fixed-variant": "#673d00",
        "md-surface": "#f8f9ff",
        "md-surface-dim": "#ccdbf4",
        "md-surface-bright": "#f8f9ff",
        "md-surface-container-lowest": "#ffffff",
        "md-surface-container-low": "#eff4ff",
        "md-surface-container": "#e5eeff",
        "md-surface-container-high": "#dce9ff",
        "md-surface-container-highest": "#d4e4fc",
        "md-surface-variant": "#d4e4fc",
        "md-on-surface": "#0d1c2e",
        "md-on-surface-variant": "#43474e",
        "md-inverse-surface": "#223144",
        "md-inverse-on-surface": "#eaf1ff",
        "md-inverse-primary": "#adc7f7",
        "md-outline": "#74777f",
        "md-outline-variant": "#c4c6cf",
        "md-error": "#ba1a1a",
        "md-error-container": "#ffdad6",
        "md-on-error": "#ffffff",
        "md-on-error-container": "#93000a",
        "md-tertiary": "#4b0004",
        "md-tertiary-container": "#73000b",
        "md-tertiary-fixed": "#ffdad6",
        "md-tertiary-fixed-dim": "#ffb3ad",
        "md-on-tertiary": "#ffffff",
        "md-on-tertiary-container": "#ff736b",
        "md-on-tertiary-fixed": "#410003",
        "md-on-tertiary-fixed-variant": "#920212",
        "md-surface-tint": "#455f88",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "marquee": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "marquee": "marquee 30s linear infinite",
        "float": "float 4s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
